### PR TITLE
small 402 cleanup

### PR DESCRIPTION
**Pull request by gsulc**
Some small changes to p402.py to make it a little easier to understand in preparation for solving issues #167 and #169 . I also improved some log statements.

I have two open questions about setup_402_state_machine(): why is it necessary to enter the "Pre-Operational" NMT state to read the pdo configurations. And why change state to "Switch on Disabled"? Shouldn't the present state be kept?

### CODE REVIEW

**Comment by af-silva** [comment]
Sorry @gsulc, I'm with some work right now... I will try to review your changes by the end of the week. 
But a quick peek at the changes seems everything is ok, I just notice a small thing in the home function, the way you set the return of the function (return right the value instead of at the end of execution) bypass the finally statement of the try-catch when returning true...

But during the weekend I will review and discuss with you.

**Comment by gsulc** [comment]
I understand. Get to it when you can.

**Comment by gsulc** [comment]
I have solutions for those tickets. If you want, I can resolve the conflicts and merge, then submit those changes. I don't want to step on people's toes though.

**Comment by af-silva** [comment]
> The return statement will execute after the finally clause. From the Python documentation:

You are absolutely right, my bad.
Today I will review and merge your changes with the code base. Keep in mind that I'm trusting the fixes are not breaking anything, at the moment I can't validate this with real hardware. 

> I have solutions for those tickets

What thickets are you referring to?

> I don't want to step on people's toes though

You are not stepping in anyone toes @gsulc, I'm happy to see people contributing code to this project.

**Pull request merged**
