### PR TITLE
PDO bit mapping

### PR DESCRIPTION
**Pull request by Muschasgrazias**
get_data method is now able to understand bit mapping

### CODE REVIEW

**Comment by Muschasgrazias** [comment]
Hm somehow the "import struct" at the start of the file is missing. Can you add this please?

**Comment by Muschasgrazias** [comment]
@christiansandberg I can't add you to the Reviewers or Assigness

**Comment by christiansandberg** [comment]
I've been meaning to have a look at it. I want to write some unit test to verify it.

**Comment by christiansandberg** [comment]
It still won't work correctly with signed values. For example if one byte is 0xFF and it contains a 4-bit signed value, the read value will be 15 instead of -1.

Anyway, supporting signed values is probably too difficult so we can skip that. But setting values should be supported so if you can implement set_data as well then I can merge it.

**Comment by Muschasgrazias** [comment]
I did a few basic test on signed 8 and 16 bit and it was working both for set and get data

**Comment by christiansandberg** [comment]
Great job! I just did some minor refactoring.

**Comment by Muschasgrazias** [comment]
Hey,
Shifting might be not faster than multiplication for small numbers check:
https://stackoverflow.com/questions/37053379/times-two-faster-than-bit-shift
In short:
>So when multiplying two integers where each fits in a 30-bit digit, this is done as a direct multiplication by the CPython interpreter, instead of working with the integers as arrays

**Comment by christiansandberg** [comment]
Interesting. Does that apply for power of as well?

**Comment by Muschasgrazias** [comment]
Good point, power has a few checks before actually executing multiplications. I would have to do benchmark tests, but in the end, shift will be faster

**Pull request merged**
