### PR TITLE
Increase export_eds() test coverage

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Moreover, don't shadow `tempfile`; use instead the parameter name of the API: *dest*.

**Comment by erlend-aasland** [comment]
I expanded the scope of the PR with 083c24c; I've split up the tests in multiple test functions, for easier debugging in case one of them fails. I also used `subTest` to for a more user-friendly response in case a test fails. Added tests for some more paths through `export_od()`.

**Review by acolomb — APPROVED** [review]

**Comment by acolomb** [comment]
Waiting for #476, as that will change the raised exception type.

**Comment by erlend-aasland** [comment]
Thank you for the review! I'll pull in `master` after #476 has landed.

**Review by acolomb — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the review! Thanks for @sveinse for the yak-shave in 5db59130423948e1e8034a67983ca00afd0269d8.

**Comment by erlend-aasland** [comment]
Ouch, I seem to have introduced a temporary file mess when running the tests. Sorry 'bout that; I'll create a PR to ensure tests are properly cleaned up.

**Pull request merged**
