### PR TITLE
Skip the "highest subindex" entry when iterating over SdoRecord

### PR DESCRIPTION
**Pull request by acolomb**
The count entry itself is not part of the data (according to CiA 301), thus should not be yielded from an iterator.  That matches the behavior of SdoArray, which also yields only the array contents.

Note that the basis of returned record sub-objects is still the subset described by the OD, which might be smaller than the actual entries accessible on the node, and less than indicated by the record's subindex 0.  Thus the count (and iteration set) is reduced by one element only if the subindex 0 was actually part of this subset.

This supersedes PR #430, with the alternative approach justified in the [last comment there](https://github.com/christiansandberg/canopen/pull/430#issuecomment-2292416333).

### CODE REVIEW

**Review by erlend-aasland — COMMENTED** [review]
Consider to also update `doc/sdo.rst` with a sentence or two similar to the added code comments.

Also, it would be nice with test for this, and by that I mean preferably to add those tests first (in a separate PR), followed by the behavioural changes (this PR) coupled with amendments to the (presumably broken) tests.

**Comment by acolomb** [comment]
All comments addressed, see #539.

**Review by erlend-aasland — APPROVED** [review]
Thanks! I can confirm that the added tests cover the affected lines, and that `test_record_iter_length` expectedly fails if applied on `master`.

**Review by erlend-aasland — APPROVED** [review]
🚀

**Pull request merged**
