### PR TITLE
Tests: improve EMCY coverage

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I'm not satisfied with `test_emcy_consumer_wait`; I'll try to come up with something less smelly tomorrow.

**Comment by erlend-aasland** [comment]
> I'm not satisfied with `test_emcy_consumer_wait`; I'll try to come up with something less smelly tomorrow.

Oh well, perhaps it's fine; testing "wait functions" is always a hassle.

Moreover, perhaps `test_emcy_get_desc` got too detailed; let me know, and I'll gladly loosen it up.

**Review by acolomb — APPROVED** [review]
Looks good to me and the tests actually pass.  If you're satisfied, we can merge it right away.

**Comment by erlend-aasland** [comment]
> Looks good to me and the tests actually pass. If you're satisfied, we can merge it right away.

If you're happy, I'm happy! Feel free to land it.

**Comment by acolomb** [comment]
More flakiness :-( @erlend-aasland 
https://github.com/christiansandberg/canopen/actions/runs/10348379278

**Comment by erlend-aasland** [comment]
> More flakiness :-( @erlend-aasland https://github.com/christiansandberg/canopen/actions/runs/10348379278

I'll get to it :)

**Comment by erlend-aasland** [comment]
Ah, it was the smelly `test_emcy_consumer_wait`!

**Comment by acolomb** [comment]
Maybe joining the timer thread in between the different steps would help?  I don't really see how it fails yet, except for maybe 25 ms being too short to work accurately and reproducibly in the CI environment.

**Pull request merged**
